gantt
    dateFormat DDD
    axisFormat %
    todayMarker off
    tickInterval 1month
    title Revisited Scenario

    section Group 1
    Time-based notifications :active, a, 0, 60d
    Targeted emails :active b, 0, 60d

    section Group 2
    In-store digital coupons : c, after a b, 60d
    Store greeters : d, after a b, 60d