gantt
    dateFormat DDD
    axisFormat %
    todayMarker off
    tickInterval 1month
    title Scenario One

    section Group 1
    Time-based notifications : a, after b, 60d
    Targeted emails :active, b, 0, 60d

    section Group 2
    In-store digital coupons : c, after b d, 60d
    Store greeters :active, d, 0, 60d