name: Validate PR

on:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
      - "labeled"
      - "unlabeled"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3
        with:
          node-version: 20.4.0
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm test
  markdown-lint:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: DavidAnson/markdownlint-cli2-action@v13
          with:
            globs: |
              **/*.md
              #**/.terraform/**/*.md
  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
  action-lint:
    name: Action Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Actionlint
      id: get_actionlint
      run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
    - name: Run Actionlint
      run: ${{ steps.get_actionlint.outputs.executable }} -color
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: ShellCheck
      uses: ludeeus/action-shellcheck@2.0.0
