name: Validate PR

on:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
      - "labeled"
      - "unlabeled"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - name: Get feed xsl
        run: |-
          npm run build:feed
      - name: Render diagrams
        run: |-
          npm run build:diagrams
      - name: Run tests
        run: |-
          npm run test -- run
      - name: Run e2e tests
        run: |-
          npm run e2e
      - name: Build website
        run: |-
          npm run build
